version: '3.7'
services:
  app:
    env_file:
      ./.env
    build: ./app
    ports:
      - "8001:80"

  db:
    build: ./db
    env_file:
      ./.env
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      - MYSQL_USER=ac2manager
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # Specify the above two passwords in `.env` file.

  ec2ctl:
    env_file:
      ./.env
    build: ./ec2ctl
    volumes:
      - "/opt/ac2manager:/opt/ac2manager"

volumes:
  db-data:
