version: '3.7'
services:
  app:
    build: ./app
    networks:
      - udnetwork

  db:
    build: ./db
    env_file:
      ./.env
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - udnetwork
    environment:
      - MYSQL_USER=ac2manager
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # Specify the above two passwords in `.env` file.

volumes:
  db-data:

networks:
  udnetwork:
